### ISSUE TITLE
Inconsistent naming in README parameters (PLAYWRIGHT vs CAMOUFOX)

### ISSUE THREAD

**Issue by tommylge** [Ehsan-U/scrapy-camoufox#1]
Hello,

Thanks for creating and maintaining this fork! I noticed a small discrepancy in the README. The documentation still refers to `PLAYWRIGHT_LAUNCH_OPTIONS` even though the code has been updated to `CAMOUFOX_LAUNCH_OPTIONS`. This might cause some confusion for new users trying to configure the project.

Would it be possible to update the README to reflect the correct parameter naming (`CAMOUFOX_LAUNCH_OPTIONS`)?
https://github.com/Ehsan-U/scrapy-camoufox?tab=readme-ov-file#camoufox_launch_options

Thank you for your work on this project!

**Comment by Ehsan-U** [comment]
@tommylge Thank You!
Updated !
